# Generated by Django 5.0 on 2023-12-04 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='user_profile')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
