# Generated by Django 5.0 on 2023-12-21 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50, null=True)),
                ('adress', models.CharField(max_length=80, null=True)),
                ('image', models.ImageField(default=False, null=True, upload_to='store/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=5)),
                ('like', models.IntegerField(default=0)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=50)),
                ('image', models.ImageField(default=False, upload_to='profile/')),
                ('is_barber', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairpro.store')),
                ('user_detail', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(through='hairpro.Team', to='hairpro.detailuser'),
        ),
        migrations.AddField(
            model_name='detailuser',
            name='stores',
            field=models.ManyToManyField(through='hairpro.Team', to='hairpro.store'),
        ),
    ]
