# Generated by Django 5.0 on 2024-01-01 01:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.store'),
        ),
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=250)),
                ('price', models.CharField(default='', max_length=50)),
                ('device', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default=False, upload_to='hairstyles/')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hairpro.store')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=50)),
                ('end', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('display', models.CharField(default='block', max_length=50)),
                ('store', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hairpro.store')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='no', max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hairstyle', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.hairstyle')),
                ('schedule', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.schedule')),
            ],
        ),
    ]
