# Generated by Django 5.0 on 2023-12-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
