# Generated by Django 5.0 on 2023-12-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='user_profile'),
        ),
    ]
