# Generated by Django 5.0 on 2023-12-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0003_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
