# Generated by Django 5.0 on 2024-01-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0003_alter_appointment_hairstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hairstyle',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='hairpro.hairstyle'),
        ),
    ]
