# Generated by Django 5.0 on 2023-12-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0004_rename_nom_user_name_remove_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pseudo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
    ]
