# Generated by Django 5.0 on 2023-12-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0005_alter_detailuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailuser',
            name='image',
            field=models.ImageField(default=False, upload_to='profile/'),
        ),
    ]
