# Generated by Django 5.0 on 2024-01-11 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0005_alter_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyle',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser'),
        ),
    ]
