# Generated by Django 5.0 on 2024-01-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0007_appointment_date_created_alter_appointment_hairstyle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
