# Generated by Django 5.0 on 2024-01-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0008_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='store',
        ),
    ]
