# Generated by Django 5.0 on 2024-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0009_remove_schedule_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
