# Generated by Django 5.0 on 2024-01-12 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0010_schedule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairstyle',
            name='store',
        ),
    ]
