# Generated by Django 5.0 on 2024-01-13 02:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0011_remove_hairstyle_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=False, upload_to='galeries/')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser')),
            ],
        ),
    ]
