# Generated by Django 5.0 on 2024-01-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0012_galerie_testimonie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user_detail',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='detailuser',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='store',
            name='users',
        ),
        migrations.RemoveField(
            model_name='team',
            name='store',
        ),
    ]
