# Generated by Django 5.0 on 2023-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0012_store_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default=False, null=True, upload_to='store/'),
        ),
    ]
