# Generated by Django 5.0 on 2024-01-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0013_rename_user_detail_team_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailuser',
            name='staff',
            field=models.IntegerField(default=0),
        ),
    ]
