# Generated by Django 5.0 on 2023-12-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0013_alter_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=5),
        ),
    ]
