# Generated by Django 5.0 on 2024-01-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0014_detailuser_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
