# Generated by Django 5.0 on 2024-01-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0016_alter_appointment_hairstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonie',
            name='text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
