# Generated by Django 5.0 on 2024-01-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0017_testimonie_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonie',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
