# Generated by Django 5.0 on 2024-01-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0018_testimonie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonie',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
