# Generated by Django 5.0 on 2024-01-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0019_alter_testimonie_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hairstyle',
            old_name='date_created',
            new_name='day_schedule',
        ),
    ]
