# Generated by Django 5.0 on 2024-01-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0020_rename_date_created_hairstyle_day_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hairstyle',
            old_name='day_schedule',
            new_name='date_created',
        ),
    ]
