# Generated by Django 5.0 on 2024-01-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0021_rename_day_schedule_hairstyle_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='like',
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='youtube',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
