# Generated by Django 5.0 on 2024-01-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0022_rename_adress_store_address_remove_store_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='status',
        ),
    ]
