# Generated by Django 5.0 on 2024-01-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0030_alter_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hairstyle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.hairstyle'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser'),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser'),
        ),
        migrations.AlterField(
            model_name='hairstyle',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser'),
        ),
        migrations.AlterField(
            model_name='testimonie',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser'),
        ),
    ]
