# Generated by Django 5.0 on 2024-01-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0031_alter_appointment_hairstyle_alter_appointment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='My Store', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='hairpro.detailuser'),
        ),
    ]
