# Generated by Django 5.0 on 2024-01-18 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0034_alter_appointment_hairstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hairpro.schedule'),
        ),
    ]
