# Generated by Django 5.0 on 2024-01-18 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairpro', '0036_alter_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hairstyle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hairpro.hairstyle'),
        ),
    ]
